### PR TITLE
datamodel: add `__check_metrics__()`

### LINKED ISSUE #267: implement datamodel.__check_metrics__
This function is supposed to be used by `Report` to determine if the selected metrics are valid, but it's currently just `pass`.

### PR DESCRIPTION
**Pull request by dplarson**
- [x] Closes #267 .
  - [x] I am familiar with the [contributing guidelines](https://solarforecastarbiter-core.readthedocs.io/en/latest/contributing.html).
  - [x] Tests added.
  - [ ] Updates entries to [`docs/source/api.rst`](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/docs/source/api.rst) for API changes.
  - [x] Adds descriptions to appropriate "what's new" file in [`docs/source/whatsnew`](https://github.com/SolarArbiter/solarforecastarbiter-core/tree/master/docs/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
  - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
  - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

Adds helper function `__check_metrics__()` to determine if the select metrics are valid (e.g. if evaluating a deterministic forecast, then should use deterministic forecast metrics, not probabilistic).

### CODE REVIEW

**Comment by dplarson** [comment]
@wholmgren This PR (adding the `__check_metrics__()` function for verifying that the selected metrics are valid for the given forecast type) is ready for review.

**Comment by wholmgren** [comment]
Looks good assuming we add follow up issue for probabilistic metrics. I think it's worth a quick note in the whats new file too.

**Comment by dplarson** [comment]
Just opened issue #302 for checking probabilistic metrics and added a line to `docs/whatsnews` about the new functionality.

**Comment by wholmgren** [comment]
@alorenzo175 ok to merge?

**Pull request merged**
