### PR TITLE
fix timeseries and scatter plot order and opacity

### LINKED ISSUE #419: make plotly scatter plot have a 1:1 aspect ratio
Want the plot to use the same amount of x and y space.

newplot(10)

Probably tricky to do while remaining responsive. We hacked around it for bokeh but it was fragile.

### LINKED ISSUE #547: Marker opacity in report scatter plot
In the report scatter plots of forecast vs observed values, using marker opacity to make markers partially transparent might make it easier to see density/trends in large datasets. For example, in the chart below, it is hard to tell if the points where GFS values are ~1/3 of observations are outliers compared to the 1:1 "cluster".

newplot

### LINKED ISSUE #548: Inconsistent plot colors in reports
In reports, it looks like the plot colors used for each data set alternate for different types of plots. Reports might be easier to follow if colors were consistent. For example, in the first two figures below, where both data sets are represented in a single plot, HRRR is blue and GFS is green. But in the second two figures, where each data set gets its own plot, HRRR is green and GFS is blue. 

newplot
newplot (1)
newplot (2)
newplot (3)

### PR DESCRIPTION
**Pull request by wholmgren**
- [x] Closes #547. closes #548  closes #419 
  - [x] I am familiar with the [contributing guidelines](https://solarforecastarbiter-core.readthedocs.io/en/latest/contributing.html).
  -  ~Tests added.~
  -  ~Updates entries to [`docs/source/api.rst`](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/docs/source/api.rst) for API changes.~
  - [x] Adds descriptions to appropriate "what's new" file in [`docs/source/whatsnew`](https://github.com/SolarArbiter/solarforecastarbiter-core/tree/master/docs/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
  - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
  - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by wholmgren** [comment]
@williamhobbs thanks again for creating these issues. Here are some examples with 9 months of hourly forecasts and observations. Do you have a favorite? 

opacity = 0.15

Screen Shot 2020-09-10 at 7 33 47 PM

opacity = 0.25

Screen Shot 2020-09-10 at 7 18 58 PM

opacity = 0.35

Screen Shot 2020-09-10 at 7 32 34 PM

opacity = 0.5

Screen Shot 2020-09-10 at 7 20 03 PM

opacity = 0.75

Screen Shot 2020-09-10 at 7 21 21 PM

opacity = 1.

Screen Shot 2020-09-10 at 7 23 16 PM


And here is opacity 0.25 and 1 with just a single forecast.

Screen Shot 2020-09-10 at 7 26 56 PM
Screen Shot 2020-09-10 at 7 27 06 PM

Feels like I'm looking at two different forecasts. Disturbing.

Personally, I think 0.25 pretty good overall. I made 0.15 and 0.35 after deciding I liked 0.25. I like 0.15 more than 0.35. The discrete points in 0.15 get hard to see, so I'll keep my vote with 0.25. The only thing I don't like about it is that the legend is kind of hard to see, but I don't want to fiddle with that in this PR.

**Comment by wholmgren** [comment]
And just a month of data for 0.25 and 1.0

Screen Shot 2020-09-10 at 7 44 29 PM

Screen Shot 2020-09-10 at 7 45 25 PM

I might prefer opacity = 1 in this case, but not strongly. I don't want to fiddle with setting opacity based on the number of points, so I think 0.25 or similar is still the overall winner.

**Comment by wholmgren** [comment]
Ah, one more... Plotly documentation recommends that we combine both marker and trace opacity.

marker opacity = 0.5, trace opacity = 0.5

Screen Shot 2020-09-10 at 7 55 37 PM

marker opacity = 0.5, trace opacity = 0.25

Screen Shot 2020-09-10 at 8 00 32 PM

I flipped back and forth between images in browser tabs and I couldn't see any benefit to specifying both opacities. So my vote is still the simple marker opacity = 0.25.

**Comment by williamhobbs** [comment]
Glad to help. These look greatly improved. 

Marker opacity of 0.25 looks like a good balance to me. Going lower might help on really large/concentrated datasets, but it would make single months hard to read. And the legend legibility becomes an issue at lower opacity.

My next thought is that uniform axis tick mark intervals might help as well, but that's pretty minor.

**Comment by wholmgren** [comment]
> My next thought is that uniform axis tick mark intervals might help as well, but that's pretty minor.

Agreed. Latest commit fixes #419.

Screen Shot 2020-09-11 at 9 16 33 AM

**Review by alorenzo175 — APPROVED** [review]

**Comment by wholmgren** [comment]
Added a quick hack to render W/m^2 as <html>W/m<sup>2</sup></html>. A more unified approach to units rendering would be better but I think we should save that for a bigger plotting refactor. Here's what it looks like.

Screen Shot 2020-09-11 at 9 57 58 AM

No need to worry about implications for pdf reports since these plots are not included in the pdfs.

I'll merge when the CI is green.

**Pull request merged**
