### PR TITLE
eliminate most test warnings

### LINKED ISSUE #385: fix warnings in test suite
Test suite emits a lot of warnings

```
2020-04-09T00:08:19.4762244Z =============================== warnings summary ===============================
2020-04-09T00:08:19.4768672Z /opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/_pytest/junitxml.py:436
2020-04-09T00:08:19.4770558Z   /opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/_pytest/junitxml.py:436: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0.
2020-04-09T00:08:19.4774161Z   Add 'junit_family=xunit1' to your pytest.ini file to keep the current format in future versions of pytest and silence this warning.
2020-04-09T00:08:19.4775461Z     _issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY, config.hook, 2)
2020-04-09T00:08:19.4775823Z 
2020-04-09T00:08:19.4776193Z solarforecastarbiter/reports/figures/tests/test_bokeh_figures.py::test_bar_subdivisions_empty_cds
2020-04-09T00:08:19.4777470Z   /home/vsts/work/1/s/solarforecastarbiter/reports/figures/bokeh_figures.py:512: FutureWarning:
2020-04-09T00:08:19.4777840Z   
2020-04-09T00:08:19.4778948Z   elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
2020-04-09T00:08:19.4779365Z 
2020-04-09T00:08:19.4780426Z solarforecastarbiter/reports/figures/tests/test_bokeh_figures.py::test_bar_subdivisions_empty_cds
2020-04-09T00:08:19.4780976Z   /home/vsts/work/1/s/solarforecastarbiter/reports/figures/bokeh_figures.py:513: FutureWarning:
2020-04-09T00:08:19.4782035Z   
2020-04-09T00:08:19.4782412Z   elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
2020-04-09T00:08:19.4782776Z 
2020-04-09T00:08:19.4783828Z solarforecastarbiter/reports/figures/tests/test_plotly_figures.py::test_bar_empty_df
2020-04-09T00:08:19.4784392Z solarforecastarbiter/reports/figures/tests/test_plotly_figures.py::test_bar_subdivisions_empty_df
2020-04-09T00:08:19.4786731Z   /opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pandas/core/ops/array_ops.py:253: FutureWarning:
2020-04-09T00:08:19.4787209Z   
2020-04-09T00:08:19.4788293Z   elementwise comparison failed; returning scalar instead, but in the future will perform elementwise comparison
2020-04-09T00:08:19.4788658Z 
2020-04-09T00:08:19.4789029Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_ghi
2020-04-09T00:08:19.4790246Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_mostly_clear
2020-04-09T00:08:19.4790819Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_immediate_observation_validation_ghi
2020-04-09T00:08:19.4792098Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_immediate_observation_validation_ghi_nones
2020-04-09T00:08:19.4793422Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_immediate_observation_validation_not_listed
2020-04-09T00:08:19.4793995Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_dni
2020-04-09T00:08:19.4795235Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_immediate_observation_validation_dni
2020-04-09T00:08:19.4796607Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_dhi
2020-04-09T00:08:19.4797186Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_immediate_observation_validation_dhi
2020-04-09T00:08:19.4798433Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_poa_global
2020-04-09T00:08:19.4799727Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_immediate_observation_validation_poa_global
2020-04-09T00:08:19.4800287Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_air_temp
2020-04-09T00:08:19.4801553Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_immediate_observation_validation_air_temperature
2020-04-09T00:08:19.4802908Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_wind_speed
2020-04-09T00:08:19.4803503Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_immediate_observation_validation_wind_speed
2020-04-09T00:08:19.4804786Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_relative_humidity
2020-04-09T00:08:19.4806086Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_immediate_observation_validation_relative_humidity
2020-04-09T00:08:19.4806645Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_daily_ghi
2020-04-09T00:08:19.4808075Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_daily_observation_validation_ghi
2020-04-09T00:08:19.4808646Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_daily_observation_validation_ghi_zeros
2020-04-09T00:08:19.4809976Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_daily_dc_power
2020-04-09T00:08:19.4811236Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_daily_observation_validation_dc_power
2020-04-09T00:08:19.4811807Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_daily_ac_power
2020-04-09T00:08:19.4813065Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_daily_observation_validation_ac_power
2020-04-09T00:08:19.4814733Z solarforecastarbiter/validation/tests/test_validator.py::test_check_timestamp_spacing
2020-04-09T00:08:19.4818317Z   /home/vsts/work/1/s/solarforecastarbiter/validation/validator.py:489: FutureWarning:
2020-04-09T00:08:19.4818688Z   
2020-04-09T00:08:19.4820260Z   The 'keep_tz' keyword in DatetimeIndex.to_series is deprecated and will be removed in a future version.  You can stop passing 'keep_tz' to silence this warning.
2020-04-09T00:08:19.4821484Z 
2020-04-09T00:08:19.4821826Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_ghi
2020-04-09T00:08:19.4823053Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_mostly_clear
2020-04-09T00:08:19.4824303Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_immediate_observation_validation_ghi
2020-04-09T00:08:19.4824900Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_immediate_observation_validation_ghi_nones
2020-04-09T00:08:19.4826157Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_daily_ghi
2020-04-09T00:08:19.4827406Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_daily_observation_validation_ghi
2020-04-09T00:08:19.4827979Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_daily_observation_validation_ghi_zeros
2020-04-09T00:08:19.4829224Z solarforecastarbiter/validation/tests/test_validator.py::test_detect_clearsky_ghi
2020-04-09T00:08:19.4831762Z   /home/vsts/work/1/s/solarforecastarbiter/validation/validator.py:720: FutureWarning:
2020-04-09T00:08:19.4832153Z   
2020-04-09T00:08:19.4833703Z   The 'keep_tz' keyword in DatetimeIndex.to_series is deprecated and will be removed in a future version.  You can stop passing 'keep_tz' to silence this warning.
2020-04-09T00:08:19.4834327Z 
2020-04-09T00:08:19.4835398Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_ghi
2020-04-09T00:08:19.4835940Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_immediate_observation_validation_ghi
2020-04-09T00:08:19.4837235Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_immediate_observation_validation_ghi_nones
2020-04-09T00:08:19.4838908Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_daily_ghi
2020-04-09T00:08:19.4840346Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_daily_observation_validation_ghi
2020-04-09T00:08:19.4843512Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_daily_observation_validation_ghi_zeros
2020-04-09T00:08:19.4844861Z   /home/vsts/work/1/s/solarforecastarbiter/validation/validator.py:734: RuntimeWarning:
2020-04-09T00:08:19.4845224Z   
2020-04-09T00:08:19.4846220Z   detect_clearsky requires regular time intervals of 15m or less
2020-04-09T00:08:19.4858632Z 
2020-04-09T00:08:19.4859272Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_mostly_clear
2020-04-09T00:08:19.4859789Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_mostly_clear
2020-04-09T00:08:19.4860338Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_mostly_clear
2020-04-09T00:08:19.4861641Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_mostly_clear
2020-04-09T00:08:19.4865063Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_mostly_clear
2020-04-09T00:08:19.4865650Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_mostly_clear
2020-04-09T00:08:19.4866933Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_mostly_clear
2020-04-09T00:08:19.4868262Z solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_mostly_clear
2020-04-09T00:08:19.4869977Z solarforecastarbiter/validation/tests/test_validator.py::test_detect_clearsky_ghi
2020-04-09T00:08:19.4871683Z solarforecastarbiter/validation/tests/test_validator.py::test_detect_clearsky_ghi
2020-04-09T00:08:19.4873348Z solarforecastarbiter/validation/tests/test_validator.py::test_detect_clearsky_ghi
2020-04-09T00:08:19.4874957Z solarforecastarbiter/validation/tests/test_validator.py::test_detect_clearsky_ghi
2020-04-09T00:08:19.4876666Z solarforecastarbiter/validation/tests/test_validator.py::test_detect_clearsky_ghi
2020-04-09T00:08:19.4878381Z solarforecastarbiter/validation/tests/test_validator.py::test_detect_clearsky_ghi
2020-04-09T00:08:19.4880038Z solarforecastarbiter/validation/tests/test_validator.py::test_detect_clearsky_ghi
2020-04-09T00:08:19.4881665Z solarforecastarbiter/validation/tests/test_validator.py::test_detect_clearsky_ghi
2020-04-09T00:08:19.4883362Z solarforecastarbiter/validation/tests/test_validator.py::test_detect_clearsky_ghi
2020-04-09T00:08:19.4885063Z solarforecastarbiter/validation/tests/test_validator.py::test_detect_clearsky_ghi
2020-04-09T00:08:19.4886748Z solarforecastarbiter/validation/tests/test_validator.py::test_detect_clearsky_ghi
2020-04-09T00:08:19.4889066Z solarforecastarbiter/validation/tests/test_validator.py::test_detect_clearsky_ghi
2020-04-09T00:08:19.4890675Z solarforecastarbiter/validation/tests/test_validator.py::test_detect_clearsky_ghi
2020-04-09T00:08:19.4892384Z solarforecastarbiter/validation/tests/test_validator.py::test_detect_clearsky_ghi
2020-04-09T00:08:19.4894133Z solarforecastarbiter/validation/tests/test_validator.py::test_detect_clearsky_ghi
2020-04-09T00:08:19.4895856Z solarforecastarbiter/validation/tests/test_validator.py::test_detect_clearsky_ghi
2020-04-09T00:08:19.4902072Z   /opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pandas/core/internals/managers.py:1542: DeprecationWarning:
2020-04-09T00:08:19.4903840Z   
2020-04-09T00:08:19.4905456Z   Support for multi-dimensional indexing (e.g. `index[:, None]`) on an Index is deprecated and will be removed in a future version.  Convert to a numpy array before indexing instead.
2020-04-09T00:08:19.4907820Z 
2020-04-09T00:08:19.4908873Z solarforecastarbiter/validation/tests/test_validator.py::test_detect_clearsky_ghi
2020-04-09T00:08:19.4909729Z   /opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pvlib/clearsky.py:721: RuntimeWarning:
2020-04-09T00:08:19.4910178Z   
2020-04-09T00:08:19.4910428Z   invalid value encountered in true_divide
2020-04-09T00:08:19.4910654Z 
2020-04-09T00:08:19.4910987Z solarforecastarbiter/validation/tests/test_validator.py::test_detect_clearsky_ghi
2020-04-09T00:08:19.4913316Z   /opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/pvlib/clearsky.py:746: RuntimeWarning:
2020-04-09T00:08:19.4913842Z   
2020-04-09T00:08:19.4914113Z   invalid value encountered in less
2020-04-09T00:08:19.4914376Z 
2020-04-09T00:08:19.4914899Z -- Docs: https://docs.pytest.org/en/latest/warnings.html
```

### PR DESCRIPTION
**Pull request by wholmgren**
- [x] Closes #385  .
  - [x] I am familiar with the [contributing guidelines](https://solarforecastarbiter-core.readthedocs.io/en/latest/contributing.html).
  - [x] Tests added.
  - [x] Updates entries to [`docs/source/api.rst`](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/docs/source/api.rst) for API changes.
  - [x] Adds descriptions to appropriate "what's new" file in [`docs/source/whatsnew`](https://github.com/SolarArbiter/solarforecastarbiter-core/tree/master/docs/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
  - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
  - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by wholmgren** [comment]
this PR: `= 3 failed, 2337 passed, 1 skipped, 44 xfailed, 11 warnings in 152.67s (0:02:32) =`

master: `= 2340 passed, 1 skipped, 44 xfailed, 70 warnings in 158.43s (0:02:38) =`

failures due to events. 

Not sure what to do about the remaining warnings. 
* The validator warnings could be fixed by supplying higher time resolution data, but wasn't sure if it was important that the data was hourly for another reason. I guess we could/should have two test data sets with different time resolution, but out of scope here.
* Silence the bokeh warnings? 
* The first `test_detect_clearsky_ghi` `RuntimeWarning` is caused by a `0. / 0.` (within np arrays). Not sure about the second. I suggest silencing the invalid runtimewarnings in this test.

**Comment by alorenzo175** [comment]
> * The validator warnings could be fixed by supplying higher time resolution data, but wasn't sure if it was important that the data was hourly for another reason. I guess we could/should have two test data sets with different time resolution, but out of scope here.
> 

I agree two sets would be best, and ok to leave for now and make an issue?

> * Silence the bokeh warnings?
> 

yes

> * The first `test_detect_clearsky_ghi` `RuntimeWarning` is caused by a `0. / 0.` (within np arrays). Not sure about the second. I suggest silencing the invalid runtimewarnings in this test.

yes

**Comment by wholmgren** [comment]
working through a few new warnings caused by recent PRs

**Comment by wholmgren** [comment]
down to 

```
=============================== warnings summary ===============================
/opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/_pytest/junitxml.py:436
  /opt/hostedtoolcache/Python/3.7.6/x64/lib/python3.7/site-packages/_pytest/junitxml.py:436: PytestDeprecationWarning: The 'junit_family' default value will change to 'xunit2' in pytest 6.0.
  Add 'junit_family=xunit1' to your pytest.ini file to keep the current format in future versions of pytest and silence this warning.
    _issue_warning_captured(deprecated.JUNIT_XML_DEFAULT_FAMILY, config.hook, 2)

solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_ghi
solarforecastarbiter/validation/tests/test_validation_tasks.py::test_immediate_observation_validation_ghi
solarforecastarbiter/validation/tests/test_validation_tasks.py::test_immediate_observation_validation_ghi_nones
solarforecastarbiter/validation/tests/test_validation_tasks.py::test_validate_daily_ghi
solarforecastarbiter/validation/tests/test_validation_tasks.py::test_daily_observation_validation_ghi
solarforecastarbiter/validation/tests/test_validation_tasks.py::test_daily_observation_validation_ghi_zeros
  /home/vsts/work/1/s/solarforecastarbiter/validation/validator.py:734: RuntimeWarning:
  
  detect_clearsky requires regular time intervals of 15m or less
```

@alorenzo175 I think this is ready to merge but worth double checking you agree with https://github.com/SolarArbiter/solarforecastarbiter-core/pull/395/commits/37a1faf9eddecbe089b997ce4c8af3bd167f4749

**Comment by alorenzo175** [comment]
I'm good with the skill adjustment

**Pull request merged**
