### PR TITLE
add probabilistic forecast classes to datamodel

### LINKED ISSUE #47: add probabilistic forecast container to data model
Should be comprised of a set of standard forecast containers

### LINKED ISSUE #125: Observation and Forecast.from_dict does not convert 'site' key to Site object
I think it should do the conversion, but it at least needs to be clearly documented if not. 

Ran into the problem when doing something like this:

```python
observation = session.get_observation('9f657636-7e49-11e9-b77f-0a580a8003e9')

# forecast intervals are 1h and labels are beginning
# make new observation that matches forecasts and resample data
obs_dict = observation.to_dict()
obs_dict['interval_label'] = 'beginning'
obs_dict['interval_length'] = 60
observation_resampled = datamodel.Observation.from_dict(obs_dict)

d = {}
d[observation] = 1  # works just fine
d[observation_resampled] = 2  # TypeError: unhashable type: 'dict'

obs_dict['site'] = observation.site
observation_resampled2 = datamodel.Observation.from_dict(obs_dict)
d[observation_resampled2] = 2  # now it works
```

### PR DESCRIPTION
**Pull request by wholmgren**
- [x] Closes #47 . closes #125
  - [x] I am familiar with the [contributing guidelines](https://solarforecastarbiter-core.readthedocs.io/en/latest/contributing.html).
  - [x] Tests added.
  - [x] Updates entries to [`docs/source/api.rst`](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/docs/source/api.rst) for API changes.
  - [x] Adds descriptions to appropriate "what's new" file in [`docs/source/whatsnew`](https://github.com/SolarArbiter/solarforecastarbiter-core/tree/master/docs/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
  - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
  - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

@alorenzo175 is this how we want to implement probabilistic forecasts in `datamodel.py`? I've forgotten what we discussed months ago.

I'll add tests once we agree on the design.

### CODE REVIEW

**Comment by alorenzo175** [comment]
I guess that is basically how it's implemented in the database, although do we want to make both subclasses of Forecast?

**Comment by wholmgren** [comment]
Yeah, not sure... I could be convinced to drop the inheritance on one of them, but I think we'll run into situations in the code in which we wish we had it on both (or the other).

**Comment by alorenzo175** [comment]
That's fine. We should use whatever dataclass options to restrict axis to x and y, and what about the names? Seems like what you call ``ProbabilisticForecastGroup`` should just be ``ProbabilisticForecast`` and the other class should be something else.

**Comment by wholmgren** [comment]
> We should use whatever dataclass options to restrict axis to x and y

Are you talking about something like a new `__check_axis__` method that's called by `__post_init__`? Otherwise I don't think dataclasses allow you to specify allowable values. Maybe could use attrs but would rather not add that complication here. 

> Seems like what you call ProbabilisticForecastGroup should just be ProbabilisticForecast and the other class should be something else.

Hmmm.... [definitions](https://solarforecastarbiter.org/definitions/#probforecastdef) page doesn't provide clear guidance on this. API documentation refers to e.g. "List Probabilistic Forecasts groups" and "Get Probabilistic Forecast data for one constant value" so again not clear guidance. Another option is avoid `ProbabilisticForecast` entirely, so something like `ProbabilisticForecastGroup` and `ProbabilisticForecastSingle`.

**Comment by alorenzo175** [comment]
Yes, I was thinking of something in a ``__post_init__``.

Hmm, I was going by what's on the dashboard. Looks like there is ``Probabilistic Forecast`` and ``Probabilistic Forecast Value``. I do like keeping the group as ``ProbabilisticForecast`` since it indicates that it is really the main thing that you should look at and evaluate.

**Comment by wholmgren** [comment]
I forgot that this simple approach won't work because the dataclass inheritance logic effectively puts positional args of the child after keyword args of the parent. Some ideas:

* use attrs instead of dataclass
* refactor `Forecast` into `ForecastBase` (all args), `ForecastExtras` (all kwargs), and `Forecast(ForecastBase, ForecastExtras)` following [this pattern](https://stackoverflow.com/a/53085935/2802993)
* copy pasta!

**Comment by alorenzo175** [comment]
base + extras is ok with me

**Comment by wholmgren** [comment]
@alorenzo175 this is mostly working now. There's something wrong with the way I'm constructing the `ProbabilisticForecast` objects for the tests, but I don't understand it well. Maybe related to how sites are passed around in the tests... Any ideas?

**Comment by alorenzo175** [comment]
You were using the wrong site id in conftest so it didn't match later.

I also adjusted the processing of Tuple[another dataclass] when loading from dict. You should look at that.

**Comment by wholmgren** [comment]
Thanks. Does this close #125?

**Comment by alorenzo175** [comment]
Probably, should add a separate test to make sure though.

**Pull request merged**
