### PR TITLE
fix resampling of obs when fx has different interval label

### LINKED ISSUE #705: interval label and resampling observations
Figure below illustrates that there is an issue with resampling observations depending on the interval label

Screen Shot 2021-08-04 at 2 23 01 PM

The issue is not in the plotting. Here's the relevant part of the csv with processed forecasts and observations:

```
,University of<br>Arizona OASIS ghi<br>60m ending,University of<br>Arizona OASIS ghi<br>60m beginning
2020-12-31T17:00:00-07:00,23.8143,23.8143
```

I believe the issue is that this block of code resampling code uses `observation.interval_label` rather than  `forecast.interval_label` to determine the resampled label.

https://github.com/SolarArbiter/solarforecastarbiter-core/blob/e65198d0b0c6805005d0ce46bcecc993fb3f0707/solarforecastarbiter/metrics/preprocessing.py#L241-L257

So this is very similar to https://github.com/SolarArbiter/solarforecastarbiter-core/pull/702#pullrequestreview-719463826

### PR DESCRIPTION
**Pull request by wholmgren**
- [x] Closes #705 .
  - [x] I am familiar with the [contributing guidelines](https://solarforecastarbiter-core.readthedocs.io/en/latest/contributing.html).
  - [x] Tests added.
  - ~Updates entries to [`docs/source/api.rst`](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/docs/source/api.rst) for API changes.~
  - [x] Adds descriptions to appropriate "what's new" file in [`docs/source/whatsnew`](https://github.com/SolarArbiter/solarforecastarbiter-core/tree/master/docs/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
  - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
  - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by wholmgren** [comment]
Turns out that plotting was messed up for two reasons. First, the data was resampled without regard for the label, as documented in the linked issue. Second, the plotting code introduced in #689 neglected to slice down to just the observation hash of interest, so ultimately we plotted the first points in `timeseries_value_df` that occurred at the right index label for the desired frequency.

Master

Screen Shot 2021-08-09 at 9 27 01 PM

This PR

Screen Shot 2021-08-09 at 9 26 52 PM

And comparison of metrics... Note that the analysis period is 2021-06-01 through 2021-12-31 and I ran the "master" report a few days ago so there are minor differences due to a longer record in "This PR". Minor changes in the NWP metrics. Hour ahead persistence is now much lower MAE, with the other intraday persistence becoming a bit worse.

Master

Screen Shot 2021-08-09 at 9 27 43 PM

This PR

Screen Shot 2021-08-09 at 9 28 18 PM

**Comment by wholmgren** [comment]
FYI @dplarson @awig this was a critical oversight in our push to 1.0 last year. You had to good sense to document it earlier in development, I just failed to follow up with an issue to track its resolution. Pandemic and contract chaos didn't help either.

**Comment by dplarson** [comment]
Thanks for letting us know and for catching the issue/already creating a fix. It's always easy to lose track of things, especially when we're all on so many different projects (not to mention non-work things).

**Review by lboeman — APPROVED** [review]

**Comment by awig** [comment]
Thanks for fixing it and thanks @dplarson for actually noting it

**Pull request merged**
