### PR TITLE
slice with consistent tz

### LINKED ISSUE #173: test_api.py failures with pandas 0.25.1
with latest pandas (0.25.1)...

```
    def test_real_apisession_get_observation_values_tz(real_session):
        start = pd.Timestamp('2019-04-14T22:00:00-0200')
        end = pd.Timestamp('2019-04-15T05:00:00-0700')
        obs = real_session.get_observation_values(
            '123e4567-e89b-12d3-a456-426655440000',
>           start, end)

ValueError: Both dates must have the same UTC offset
```

```
    def test_real_apisession_get_forecast_values_tz(real_session):
        start = pd.Timestamp('2019-04-14T20:00:00-0400')
        end = pd.Timestamp('2019-04-15T13:00:00+0100')
        fx = real_session.get_forecast_values(
            'f8dd49fa-23e2-48a0-862b-ba0af6dec276',
>           start, end)

ValueError: Both dates must have the same UTC offset
```

@alorenzo175 change the tests to pass uniform tzs or change the code to convert tzs?

### PR DESCRIPTION
**Pull request by wholmgren**
- [x] Closes #173 .
  - [x] I am familiar with the [contributing guidelines](https://solarforecastarbiter-core.readthedocs.io/en/latest/contributing.html).
  - [x] Tests added.
  - [x] Updates entries to [`docs/source/api.rst`](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/docs/source/api.rst) for API changes.
  - [x] Adds descriptions to appropriate "what's new" file in [`docs/source/whatsnew`](https://github.com/SolarArbiter/solarforecastarbiter-core/tree/master/docs/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
  - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
  - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

There are a couple of additional places in the code that use `.loc[start:end]` but they are not likely to be passed inconsistent timezones, so I don't think this is worth handling more generally.

### CODE REVIEW

**Comment by wholmgren** [comment]
Test failure unrelated.

**Comment by wholmgren** [comment]
Hm, not sure what to do in that case. Maybe don't convert and let pandas raise the exception if necessary.

**Comment by alorenzo175** [comment]
yeah better than silent bug

**Comment by wholmgren** [comment]
Added a test to document the behavior. Arguable if that's what the behavior should be.

**Comment by alorenzo175** [comment]
I guess I would rather raise an exception than do something unexpected. Data should always be localized (except maybe when empty)

**Comment by wholmgren** [comment]
Ok, I think this is ready.

**Pull request merged**
