### PR TITLE
plot all observation values in time series

### PR DESCRIPTION
**Pull request by wholmgren**
- [ ] Closes #xxxx .
  - [x] I am familiar with the [contributing guidelines](https://solarforecastarbiter-core.readthedocs.io/en/latest/contributing.html).
  - [ ] Tests added.
  - [ ] Updates entries to [`docs/source/api.rst`](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/docs/source/api.rst) for API changes.
  - [x] Adds descriptions to appropriate "what's new" file in [`docs/source/whatsnew`](https://github.com/SolarArbiter/solarforecastarbiter-core/tree/master/docs/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
  - [ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
  - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

The issue with the missing observations in time series plots is due to the fact that the processed observations are only plotted for the first instance of that processed observation. In the TA2 reports, the PNNL forecast is the first forecast/observation pair, so it gets the first pair index assigned to it during plotting. But that forecast has not yet been uploaded, so the observations are all dropped for that pair (recall missing forecasts are dropped on a forecast by forecast basis). And then there is nothing to plot.

This PR changes the observation plotting algorithm. The net result is that we plot the union of processed observations for all pairs.

Prod

Screen Shot 2021-07-21 at 2 52 36 PM

This PR

Screen Shot 2021-07-21 at 2 52 51 PM

I'm not aware of any good automated ways to test this.

### CODE REVIEW

**Comment by lboeman** [comment]
This appears to have fixed the issue for some of the reports, but for reports like http://localhost:8080/reports/fc8eaa66-b289-11eb-9105-0a580a8002ec, observations are still not being plotted.

**Comment by lboeman** [comment]
Found the bug here. For some reason, the report linked above has an extra timestamp at the beginning for the second pair that occurs before the first pair. in this case, pair one looks like this:
```
timestamp                                                                                                
2018-01-01 10:00:00-08:00           1           97.338150          62.6910                               
2018-01-01 11:00:00-08:00           1          116.819167          96.0788                               
2018-01-01 12:00:00-08:00           1          150.398333         112.9840
2018-01-01 13:00:00-08:00           1          147.845167         118.9730
2018-01-01 14:00:00-08:00           1           93.385300          95.5101
...                               ...                 ...              ...
```

and pair 2:
```
timestamp                                                                  
2018-01-01 00:00:00-08:00           2           -0.348940            30.43
2018-01-01 10:00:00-08:00           2           97.338150           104.86
2018-01-01 11:00:00-08:00           2          116.819167           166.61
2018-01-01 12:00:00-08:00           2          150.398333           212.91
2018-01-01 13:00:00-08:00           2          147.845167           218.90
...                               ...                 ...              ...
```
And then when deduped, there is a trailing value before the start of the series which raises problems when the time range is pulled from the first and last index of the data in `_fill_timeseries` here: https://github.com/SolarArbiter/solarforecastarbiter-core/blob/63f9a0e6f0976e786755a49b359f40f5b09c507e/solarforecastarbiter/reports/figures/plotly_figures.py#L237-L239. We could solve this by sorting the index in `_fill_timeseries`, or by selecting only a single `pair_index` before filling. I think that sorting is probably the way to go, as that extra point only exists in a handful of the forecasts. Seems like maybe something wonky is happening with the filtering where it has trouble catching the first poing for ending labelled data?

**Comment by wholmgren** [comment]
I think the commit I pushed last night fixed this right?

**Comment by lboeman** [comment]
> I think the commit I pushed last night fixed this right.
Yep, sorry, missed that commit and was looking at my your branch from yesterday afternoon.

**Comment by wholmgren** [comment]
@lboeman can you approve and merge if you're happy with it?

**Review by lboeman — APPROVED** [review]

**Pull request merged**
