### PR TITLE
change stale, interpolated windows, add daytime-only derived masks

### LINKED ISSUE #124: stale and interpolated values
The validator's detect stale and interpolated values functions flag points at night, though the details depend on the observation (two examples below). Is this desirable? Say you want to include nighttime values in your analysis but you want to exclude stale/interpolated points. You'd need to make a new flag `(STALE | INTERPOLATED) & ~NIGHTTIME`. If we wanted to exclude nighttime from the flag, then the detect functions would need to know when it was nighttime. So work to be done either way.

During the day, the stale/interpolated values functions sometimes flag data that is not actually stale or interpolated.

Screen Shot 2019-06-06 at 1 22 20 PM
Screen Shot 2019-06-06 at 1 20 24 PM

### PR DESCRIPTION
**Pull request by wholmgren**
- [x] Closes #124  .
  - [x] I am familiar with the [contributing guidelines](https://solarforecastarbiter-core.readthedocs.io/en/latest/contributing.html).
  - [x] Tests added.
  - ~Updates entries to [`docs/source/api.rst`](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/docs/source/api.rst) for API changes.~
  - [x] Adds descriptions to appropriate "what's new" file in [`docs/source/whatsnew`](https://github.com/SolarArbiter/solarforecastarbiter-core/tree/master/docs/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
  - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
  - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by wholmgren** [comment]
Example:

```python
latitude = 32.2
longitude = -110.9
elevation = 700

site = datamodel.Site(
    name='Tucson, AZ',
    latitude=latitude,
    longitude=longitude,
    elevation=elevation,
    timezone='America/Phoenix'
)

observation = datamodel.Observation(
    name='GHI', variable='ghi',
    interval_value_type='mean',
    interval_length=pd.Timedelta('15min'),
    interval_label='beginning', site=site, uncertainty=1)

start = pd.Timestamp('20200519 0700')
end = pd.Timestamp('20200522 0700')
index = pd.date_range(start=start, end=end, freq='15min')
cs = location.get_clearsky(index)

values = cs['ghi'].copy()
values.loc['20200519 1500':'20200519 1600'] = 550
values.loc['20200520 1500':'20200520 1800'] = 550
validation_flags = tasks.validate_daily_ghi(observation, values)
quality_flags = pd.Series(2, index=index)
for flag in validation_flags:
    quality_flags |= flag
data = pd.DataFrame({'value': values, 'quality_flag': quality_flags})

out = timeseries.generate_observation_figure(observation, data)
show(out)
```

Screen Shot 2020-05-22 at 8 07 46 AM

**Comment by wholmgren** [comment]
After initial review, I think we need to solve #123 at the same time. The example above (typical of PI systems) shows that we're going to need a robust LIMITS EXCEEDED in addition to the DAYTIME STALE VALUES.

**Comment by alorenzo175** [comment]
> Edit 2: Now I'm worried about the actual LIMITS EXCEEDED flag. I have to go above 2 x the clearsky value to activate it.

I don't see it activated at all during the daytime

**Comment by cwhanse** [comment]
> another edit to show that 2.05 x clear sky GHI activates it.
> @cwhanse is the LIMITS EXCEEDED flag behaving as you'd expect it to? I don't understand the behavior.

Yes. The QCRad algorithm being used for LIMITS EXCEEDED specifies a physically-possible upper bound, globally and at any time scale.  So over-irradiance as discussed in #123 will pass the physical limit test.  See Figure 1-3 in [Long's paper](ftp://ftp.cmdl.noaa.gov/g-rad/isis/qcrad_v3/Long_TOAtmosJ.pdf).

**Comment by wholmgren** [comment]
from https://github.com/SolarArbiter/solarforecastarbiter-core/issues/123#issuecomment-536735672:

> check_irradiance_limits_QCRad will flag GHI > extraterrestrial, so it will flag over-irradiance. 

but from https://github.com/SolarArbiter/solarforecastarbiter-core/blob/8ef997ee71a44c65c68dc5f58ae44feab39eb333/solarforecastarbiter/validation/validator.py#L20 it appears the limit is actually 1.5 * extraterrestrial, right? Perhaps that limit comes from the original code, because I don't see it the paper.

**Comment by cwhanse** [comment]
>  it appears the limit is actually 1.5 * extraterrestrial, right? Perhaps that limit comes from the original code, because I don't see it the paper.

`min` + `mult` * extraterrestrial * cos(zenith) ^ `exp`

Equation at the top of page 25 of the paper at ftp://ftp.cmdl.noaa.gov/g-rad/isis/qcrad_v3/Long_TOAtmosJ.pdf

**Comment by wholmgren** [comment]
Thanks - I was looking at Long and Ackerman. I plotted `validator._QCRad_ub` and agree that the function is faithful to the reference and working as intended. 

I think this is ready to merge.

**Pull request merged**
