### PR TITLE
further support for probabilistic forecasts in reports

### PR DESCRIPTION
**Pull request by wholmgren**
- [ ] Closes #xxxx .
  - [ ] I am familiar with the [contributing guidelines](https://solarforecastarbiter-core.readthedocs.io/en/latest/contributing.html).
  - [ ] Tests added.
  - [ ] Updates entries to [`docs/source/api.rst`](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/docs/source/api.rst) for API changes.
  - [ ] Adds descriptions to appropriate "what's new" file in [`docs/source/whatsnew`](https://github.com/SolarArbiter/solarforecastarbiter-core/tree/master/docs/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
  - [ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
  - [ ] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

Partly trying to understand where we're at, partly trying to address #266 and #425.

A report with a `ProbabilisticForecastConstantValue` now stops during metrics calculation because it expects a DataFrame of constant values instead of a single series. A report with a `ProbabilisticForecast` stops when making graphs because a tuple of metric results is passed instead of a single metric result.

testing against json schema like:

<details>

```
{
    "report_parameters": {
        "name": "test",
        "start": "2019-08-25T00:00:00Z",
        "end": "2019-12-03T00:00:00Z",
        "filters": [
            {"quality_flags": [
                "USER FLAGGED",
                "NIGHTTIME",
                "CLEARSKY"
            ]}
        ],
        "metrics": [
            "bs"
        ],
        "categories": [
            "total"
        ],
        "object_pairs": [
            {
                "observation": "9dfe124a-7e49-11e9-98c3-0a580a8003e9",
                "forecast": "a1fc6490-080a-11ea-a9db-0a580a8003a5",
                "forecast_type": "probabilistic_forecast_constant_value"
            }
      ]
    }
  }
```

```
{
    "report_parameters": {
        "name": "test",
        "start": "2019-08-25T00:00:00Z",
        "end": "2019-12-03T00:00:00Z",
        "filters": [
            {"quality_flags": [
                "USER FLAGGED",
                "NIGHTTIME",
                "CLEARSKY"
            ]}
        ],
        "metrics": [
            "crps"
        ],
        "categories": [
            "total"
        ],
        "object_pairs": [
            {
                "observation": "9dfe124a-7e49-11e9-98c3-0a580a8003e9",
                "forecast": "a1e8b4c0-080a-11ea-897c-0a580a8003a5",
                "forecast_type": "probabilistic_forecast"
            }
      ]
    }
  }
```

</details>

### CODE REVIEW

**Comment by wholmgren** [comment]
@alorenzo175 @awig looking for your thoughts on how to refactor the metrics code to integrate with reports. @awig I vaguely recall you might have already been looking into this.

@lboeman is close to having dashboard support ready. In his prototype, the constant value objects are specified independently of the group objects. The json schema in the details tab above also encodes this. So we might want the `calculator` code to be more discerning about the metrics it calculates and hopefully avoid the need for a different return type.

**Comment by alorenzo175** [comment]
I'm not sure how to refactor either. We probably want a standard from returned from ``calculator.calcuate_metrics``. Maybe that means ``calculate_probabilistic_metrics`` returns a list and the ``calc_metrics`` list gets extended instead of appended. Then more logic would have to go into plotting the metric result. Or maybe there is a better structure to return from calculate_metrics?

**Comment by awig** [comment]
I've blocked off the rest of the day to work on this. 

I didn't think about only passing a single `ProbabilisticForecastConstantValue` being passed directly of `ProbabilisticForecast`. Sorry I'll work on fixing so that the calculator only expects one instance of each of these and add specific tests in both `calculator` and `preprocessing`.  I expect that than this should return only a single `MetricResult` as you would like for the reports. 
Does this sound right?  If so, let me know and I'll see if I can get this done today.

**Comment by wholmgren** [comment]
@awig not your fault, we're all still working out what makes sense at all layers of the stack.

If you haven't seen it, check out @lboeman's pairs examples here https://github.com/SolarArbiter/solarforecastarbiter_dashboard/pull/238#issuecomment-624893323

There are 4 `ProbabilisticForecastConstantValues` to be evaluated (2 with reference forecasts) and 1 `ProbabilisticForecast`. That makes 5 separate `object_pairs` to be evaluated. Note the json schema example hidden under `details` in my original post.

Regarding return types, I think @alorenzo175's suggestion above makes sense, but it's hard to know until we see it in practice.

**Comment by awig** [comment]
> If you haven't seen it, check out @lboeman's pairs examples here [SolarArbiter/solarforecastarbiter_dashboard#238 (comment)](https://github.com/SolarArbiter/solarforecastarbiter_dashboard/pull/238#issuecomment-624893323)

Yeah, those look good. That gives me a clear idea of what to expect in terms of the `ForecastObservation` (or possible `ForecastAggregate`) pairs to expect.

> There are 4 `ProbabilisticForecastConstantValues` to be evaluated (2 with reference forecasts) and 1 `ProbabilisticForecast`. That makes 5 separate `object_pairs` to be evaluated. Note the json schema example hidden under `details` in my original post.

I see now you have `forecast_type` added to the pairs (that's nice so you don't have to make a request to get the object before knowing how what to do next with it).

> Regarding return types, I think @alorenzo175's suggestion above makes sense, but it's hard to know until we see it in practice.

I'm not quite sure I understand what it gets extended by. @alorenzo175 do you mind clarifying? Anyways so, `calculate_metrics` should  provide a `MetricResult` per `ForecastObservation` (and each of these is only one forecast being either deterministic, event, distribution for probabilist forecast or an individual probabilistic constant value) pair with a tuple of `MetricsValues` per individual metric value calculated. Right? Agreed that until we see it in action things might not be clear, but if I stick with this design pattern in mind I can hopefully make it work.

@wholmgren I will merge with your branch before continuing with any changes. Will that work?

**Comment by wholmgren** [comment]
Sounds good

**Comment by awig** [comment]
@alorenzo175 Are you thinking of a new data model is needed that is returned by calculate_metrics like `AggregateMetricResults` that has something akin to:

```python
@dataclass(frozen=True)
class AggregateMetricResults(BaseModel):
    report_id : str
    values : Tuple[MetricResult, ...]
    forecast_id : Union[str, None] = None   # this would come from ForecastObservation.forecast.forecast_id
```

**Comment by alorenzo175** [comment]
What I meant by extended, is that the ``calculate_metrics`` function calls ``calculate_probabilistic_metrics`` and appends them to a ``calc_metrics`` list. Since ``calculate_probabilistic_metircs`` returns a tuple of ``MetricResults``, we can call ``calc_list.extend(calculate_probabilistic_metrics...`` instead of append so the result of ``calculate_metrics`` is a single layer list of ``MetricResults``

**Comment by awig** [comment]
> What I meant by extended, is that the `calculate_metrics` function calls `calculate_probabilistic_metrics` and appends them to a `calc_metrics` list. Since `calculate_probabilistic_metircs` returns a tuple of `MetricResults`, we can call `calc_list.extend(calculate_probabilistic_metrics...` instead of append so the result of `calculate_metrics` is a single layer list of `MetricResults`

Ah, I see I was confusing extend with something else. Thanks for clarifying. I can see how this makes things easier for the reporting.

**Comment by alorenzo175** [comment]
> @alorenzo175 Are you thinking of a new data model is needed that is returned by calculate_metrics like ~`AggregateMetricResults`~ `ReportMetricResults` that has something akin to:
> 
> ```python
> @dataclass(frozen=True)
> class ReportMetricResults(BaseModel):
>     report_id : str
>     values : Tuple[MetricResult, ...]
>     forecast_id : Union[str, None] = None   # this would come from ForecastObservation.forecast.forecast_id
> ```
> 
> _Edited as Aggregate could be confusing so changed to Report_

I think as this has been flushed out more in the api/dashboard, extending the list instead of appending and adding a ``forecast_type`` (or ``metric_type``) to ``MetricResult`` (like https://github.com/SolarArbiter/solarforecastarbiter-api/pull/237/files) will be enough information for the reports to know how to proceed

**Comment by awig** [comment]
Just finished refactoring the calculator for probabilistic forecasts. I'll check how the preprocessing is working tomorrow.

**Comment by wholmgren** [comment]
#445 does all this and more. I think the only part of discussion that's still open is captured in #449.

**Pull request closed without merging**
