### PR TITLE
Sort tables and graphs

### LINKED ISSUE #796: [SFAII] improve reports with ability to sort graphs/tables by metric values
- [x] sort table columns ascending/descending
- [x] sort graphics (see if we can add a button to sort them by value instead of default in the chart)

### PR DESCRIPTION
**Pull request by awig**
- [x] Closes #796 .
  - [x] I am familiar with the [contributing guidelines](https://solarforecastarbiter-core.readthedocs.io/en/latest/contributing.html).
  - [x] Tests added or updated, no tests made for checking sorting as isn't straightforward to add javascript tests in pytest that I can find
  - [ ] Updates entries to [`docs/source/api.rst`](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/docs/source/api.rst) for API changes.  - NOT APPLICABLE
  - [x] Adds descriptions to appropriate "what's new" file in [`docs/source/whatsnew`](https://github.com/SolarArbiter/solarforecastarbiter-core/tree/master/docs/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
  - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
  - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

Add table and figure sorting, see #796

### CODE REVIEW

**Comment by awig** [comment]
Following breaking version changes required for CI tests:
- Jinja2<3.1 due to Markup safe import change
- Scipy<1.10 due to ``cannot import name 'PearsonRConstantInputWarning' from 'scipy.stats'``
- importlib-metadata<5 due to Entrypoint object attribute errors 

Version 3.7 is no okay but 3.8 and 3.9 fail with what seems like some pandas issues.

**Comment by awig** [comment]
- pandas was required to be <1.4 to avoid multiple failures.

**Comment by awig** [comment]
@dplarson 

This should be good to go. The remaining errors were all dependency issues which I've updated setup.py requirements.

I've also added a whatsnew for release 1.0.14, but I think with other changes we should maybe target a minor instead of patch release especially changing to include net load and wind.

**Review by dplarson — APPROVED** [review]
I'm comfortable with these code changes and I also confirmed the functionality by running the dashboard locally with this PR code.

**Pull request merged**
