### PR TITLE
persistence_scalar_index limits

### LINKED ISSUE #107: add limits and/or tz checking to persistence_scalar_index forecasts
`persistence_scalar_index` computes ratios of values to clear sky expectations. It's easy to get unphysical forecasts when the input data is inconsistent with the input observation location metadata. 

Maybe raise an exception if any clear sky index is larger than ~2.

### PR DESCRIPTION
**Pull request by wholmgren**
- [x] Closes #107 .
  - [x] I am familiar with the [contributing guidelines](https://solarforecastarbiter-core.readthedocs.io/en/latest/contributing.html).
  - [x] Tests added.
  - [x] Updates entries to [`docs/source/api.rst`](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/docs/source/api.rst) for API changes.
  - [x] Adds descriptions to appropriate "what's new" file in [`docs/source/whatsnew`](https://github.com/SolarArbiter/solarforecastarbiter-core/tree/master/docs/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
  - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
  - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

Adds `.clip(lower=0, upper=2)` to the clear sky index array *before* the average clear sky is computed. I think this is a reasonable approach, but I suppose others could disagree.

I considered adding keyword arguments to `persistence_scalar_index` to provide some flexibility for the user. A disadvantage of adding flexibility is that it means you have to be more explicit about the runtime configuration of a reference forecast.

What do you think @cwhanse @alorenzo175?

### CODE REVIEW

**Comment by cwhanse** [comment]
I think it's reasonable. Could use a kwarg `max_index` and `.clip(lower=0, upper=max_index)` but that's nice to have, not required.

**Comment by alorenzo175** [comment]
I'm ok with it as long as the default is reasonable so we just use the default for reference forecasts

**Comment by wholmgren** [comment]
Thanks. Then I'll suggest that we skip the kwarg for now. In that case I think this is ready to merge, except that I'd like to wait for #150 so that I can add a note to its 1.0.0b whats new file.

**Comment by wholmgren** [comment]
I think this is ready to merge.

Here's the example from the Denver workshop notebook run with and without the limit...

## Without limit (old behavior)

bokeh_plot(6)

## With limit (proposed behavior)

bokeh_plot(5)

**Pull request merged**
