### PR TITLE
Add deterministic metrics

### LINKED ISSUE #114: Add deterministic metric functions (standalone)
Add functions for computing deterministic forecast evaluation metrics, all of which are standalone functions (i.e. they only require as input the measured and predicted time-series, and do not perform any pre-processing of the data). In other words, these are the lowest level functions for computing the metrics, with the assumption that higher-level functions would call the functions as needed (e.g. after aligning and resampling time-series).

Current list of deterministic metrics:
- [ ] mean absolute error (MAE)
- [ ] mean bias error (MBE)
- [ ] mean absolute percentage error (MAPE)
- [ ] root mean square error (RMSE)
- [ ] normalized RMSE (nRMSE)
- [ ] centered (unbiased) RMSE (cRMSE)
- [ ] Pearson correlation coefficient (r)
- [ ] coefficient of determination (R^2)
- [ ] Kolmogorov-Smirnov Integral (KSI)
- [ ] the OVER metric (OVER)
- [ ] forecast skill (s)
- [ ] combined performance index (CPI)

Notes:
- this issue is related to #4 
- a separate issue will be opened for tracking the probabilistic forecast metrics
- other metrics may be added later

### PR DESCRIPTION
**Pull request by dplarson**
- [x] Closes #114.
  - [x] I am familiar with the [contributing guidelines](https://solarforecastarbiter-core.readthedocs.io/en/latest/contributing.html).
  - [x] Tests added.
  - [x] Updates entries to [`docs/source/api.rst`](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/docs/source/api.rst) for API changes.
  - [x] Adds descriptions to appropriate "what's new" file in [`docs/source/whatsnew`](https://github.com/SolarArbiter/solarforecastarbiter-core/tree/master/docs/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
  - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
  - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

Add (standalone) functions for computing deterministic forecast error metrics to the `metrics` subpackage, including adding tests and updating the `reports` subpackage to use the functions. There are other metrics and functionality to be added to the `metrics` subpackage, but those will be addressed in future PRs.

Also, the commits from this PR could be squashed prior to merging.

### CODE REVIEW

**Comment by wholmgren** [comment]
`datamodel.Reports` dataclass spec includes allowable metrics. Not sure if we should make it less descriptive or if we should import a more descriptive list from the metrics module.

**Comment by dplarson** [comment]
I'll start by revising the tests as suggested.

**Comment by dplarson** [comment]
@wholmgren I still have more tests to add, but does what I added in d388df4 match with what you were thinking?

**Comment by wholmgren** [comment]
I was thinking of more simple, explicit inputs like `true = [0, 1, 2]; test = [1, 0, 2]` (but with appropriate types) and then asserting an exact value (e.g. `mbe == 0`, `mae == 2/3`). I think it's easier for someone to verify that the code is correct if it uses explicit input values.

**Comment by dplarson** [comment]
Gotcha. I'll revise accordingly.

**Comment by wholmgren** [comment]
@dplarson looks good, thanks! I think we merge this after you've updated the API and whats new documentation. @alorenzo175 any concerns/suggestions?

**Comment by alorenzo175** [comment]
Looks OK to me.

**Comment by dplarson** [comment]
@wholmgren I've added commits updating the API and what's new docs.

**Comment by wholmgren** [comment]
@dplarson was there a reason that you didn't add KSI, OVER, and CPI in this PR? Just expediency? If so, can you make a new issue so that we don't forget about them? I feel like I might have forgotten a conversation about this.

**Comment by dplarson** [comment]
@wholmgren It was primarily a timing thing. (I had meant to follow-up later, but forgot. So thanks for the reminder.)

I'll open a separate issue for KSI, OVER and CPI and then a PR to add them.

**Pull request merged**
