### PR TITLE
metrics: preprocessing: handle empty obs Series

### LINKED ISSUE #295: Add empty series to preprocessing tests
So we catch any issues like doing ``pd.DataFrame().agg('mean')['mean']`` results in a KeyError

### PR DESCRIPTION
**Pull request by dplarson**
- [x] Closes #295 .
  - [x] I am familiar with the [contributing guidelines](https://solarforecastarbiter-core.readthedocs.io/en/latest/contributing.html).
  - [x] Tests added.
  - [ ] Updates entries to [`docs/source/api.rst`](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/docs/source/api.rst) for API changes.
  - [ ] Adds descriptions to appropriate "what's new" file in [`docs/source/whatsnew`](https://github.com/SolarArbiter/solarforecastarbiter-core/tree/master/docs/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
  - [x] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
  - [x] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

### CODE REVIEW

**Comment by dplarson** [comment]
@alorenzo175 Do these tests (fully) cover the issues discussed in #295?

**Comment by alorenzo175** [comment]
Not quite. Need to also test when the observation series is empty and has a frequency < forecast. Also, that sentry error apparently only occurs when ``dtype=object``, so test an observation series that is something like
```python
EMPTY_OBJ_SERIES = pd.Series([], dtype=object, name='value', index=pd.DatetimeIndex([], freq='10min', tz='MST', name='timestamp'))
```

**Comment by dplarson** [comment]
Thanks for clarifying. I'll revise accordingly.

**Comment by dplarson** [comment]
I revised so that `resample_and_align()` checks bot if `fx.interval_length > obs.interval_length` and that neither the `fx` or `obs` Series are empty. If either `fx` or `obs` are empty (but they have the correct interval lengths), then the empty `obs` is returned without resampling.

**Comment by dplarson** [comment]
> I revised so that `resample_and_align()` checks both if `fx.interval_length > obs.interval_length` and that neither the `fx` or `obs` Series are empty. If either `fx` or `obs` are empty (but they have the correct interval lengths), then the empty `obs` is returned without resampling.

Actually, we might just need to check that `obs` isn't empty (i.e. remove the check for whether `fx` is empty).

**Comment by dplarson** [comment]
@alorenzo175 Are we okay with the implemented fix to handle empty `obs` or would it be better to raise an error instead?

**Comment by dplarson** [comment]
Looking through the code, I realized that empty `obs` and `fx` are already caught in the `metrics.calculator` code (when iterating over the selected metrics): https://github.com/SolarArbiter/solarforecastarbiter-core/blob/20cee821dd0c872d6878fe3d7d5e92d9e23e4cd6/solarforecastarbiter/metrics/calculator.py#L144-L148

Therefore, do we actually need the changes proposed in this PR?

**Comment by alorenzo175** [comment]
> @alorenzo175 Are we okay with the implemented fix to handle empty `obs` or would it be better to raise an error instead?

I think keeping it as is returning an empty series is most consistent. This will also happen if somehow the observation and forecast series are not empty but share no common indices.

> Therefore, do we actually need the changes proposed in this PR?

Definitely, we shouldn't assume this will only be used to feed the metrics calculator and at the very least, we want a helpful error message vs a hard to decipher KeyError

**Comment by dplarson** [comment]
I added an entry to `docs/source/whatsnews/1.0.0b4.rst`, listing this PR has a Bug Fix.

**Pull request merged**
