### PR TITLE
metrics: add summary statistics

### LINKED ISSUE #231: Add summary stat functions for observations and forecasts
Add functions (probably to the Metrics module) that cover commonly requested summary statistics of the observations and forecasts, e.g., min, max, mean and standard deviation.

This issue is in response to discussion from #230 (quoted below for ease of reference):

> Maybe a new issue, but we could expand the scope of this PR: should we also add functions for statistics of the observations/forecasts? Maybe just mean and std dev for now. I think our functions would just return the numpy operations, but it would formalize their availability in our package. In either case, I'd like to eventually present those statistics in the reports so it will need to be calculated somewhere.

### PR DESCRIPTION
**Pull request by dplarson**
- [x] Closes #231 .
  - [x] I am familiar with the [contributing guidelines](https://solarforecastarbiter-core.readthedocs.io/en/latest/contributing.html).
  - [x] Tests added.
  - [ ] Updates entries to [`docs/source/api.rst`](https://github.com/SolarArbiter/solarforecastarbiter-core/blob/master/docs/source/api.rst) for API changes.
  - [ ] Adds descriptions to appropriate "what's new" file in [`docs/source/whatsnew`](https://github.com/SolarArbiter/solarforecastarbiter-core/tree/master/docs/source/whatsnew) for all changes. Includes link to the GitHub Issue with `` :issue:`num` `` or this Pull Request with `` :pull:`num` ``. Includes contributor name and/or GitHub username (link with `` :ghuser:`user` ``).
  - [ ] New code is fully documented. Includes [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html) compliant docstrings, examples, and comments where necessary.
  - [ ] Maintainer: Appropriate GitHub Labels and Milestone are assigned to the Pull Request and linked Issue.

This PR adds `solarforecastarbiter.metrics.summary`, which contains functions for computing summary statistics of observations/forecasts (e.g. min, max, mean and std). These summary statistics will eventually be incorporated into the report interface (which will be addressed in subsequent PRs).

### CODE REVIEW

**Comment by dplarson** [comment]
@wholmgren Before I go too far with this PR, is this the direction you were thinking for the summary statistics? If so, what level of documentation and testing is needed (e.g. full docstrings + tests per function or something more minimal given that the summary functions are mainly just wrapping numpy functions)?

**Comment by wholmgren** [comment]
I don't think we need detailed docstrings. I guess it's good to test behavior in the presence of nans. 

Do you think we'd be ok skipping these wrappers and only defining the `_MAP` dictionary in terms of the numpy functions? It seems unlikely that any direct user of the python code would ever want to call our versions of these functions.

Why did you choose to go with the nan versions of the functions in this PR?

**Comment by dplarson** [comment]
> Do you think we'd be ok skipping these wrappers and only defining the `_MAP` dictionary in terms of the numpy functions? It seems unlikely that any direct user of the python code would ever want to call our versions of these functions.

I agree with your point and think we'll be okay with no wrappers. I'll revise accordingly.


> Why did you choose to go with the nan versions of the functions in this PR?

I was originally thinking that there may be cases where these summary functions would be called before/without the validation and preprocessing steps, and therefore the functions would need to handle inputs with nan values. But reflecting on this, I don't think that's likely to be a real concern. So I'll switch back to the non-nan versions (`np.mean()`, `np.min()`, etc.).

**Comment by dplarson** [comment]
@wholmgren I've revised to just defining the `_MAP` dictionary (rather than adding full wrappers to the numpy functions) and adding (simple) tests to confirm the functions work as expected when called via the `_MAP` dictionary.

**Comment by dplarson** [comment]
Do I need to add anything to `docs/api` or `docs/whatsnews` about this PR? I would think no since the the summary metrics will only be used "internally" by other parts of the codebase.

**Comment by wholmgren** [comment]
@dplarson I agree we can skip the documentation. Thanks!

**Pull request merged**
