### PR TITLE
Update license

### PR DESCRIPTION
**Pull request by lboeman**
Adds missing 1.0.13 to index, updates license to 2022/Univsersity of Arizona.

### CODE REVIEW

**Comment by lboeman** [comment]
> @lboeman for the license, I've never been clear if you need to continuously update the year or can just keep the year when the license was originally defined. It would be good to clarify that (assuming there is some official guidance somewhere on MIT licenses for open-source software).

I believe the copyright date should be updated to reflect the year that the codebase was last updated. I'm not sure if there is official guidance, but that's . I will note that the changes in this PR were at the request of UofA administration to demarcate the conclusion of the project being hosted there.

**Comment by dplarson** [comment]
Thanks for the feedback. I don't have an issue with changing the year, but good to confirm. I'm going through other open PRs (on this repo and others) and will plan on approving/merging the changes in this week.

**Comment by dplarson** [comment]
I forgot to merge this before merging PR #802, which also updated the `whatsnew` list to include `1.0.13`. Hence the extra commit to resolve the conflict.

**Review by dplarson — APPROVED** [review]
I am approving this based on information provided by Leland (from folks at the University of Arizona) regarding the need to update the copyright year line as part of EPRI taking over stewardship of the Solar Forecast Arbiter. But as a note for future discussion, we (the maintainers/contributors) should speak with the appropriate experts regarding this and related topics so we can have clearer guidance on how all of this is supposed to work. For example, does the copyright year need to be updated every time we release a tagged version? Similarly, does the copyright need to list all organizations that have contributed code? I'm not entirely sure, but I know there are experts on this that we can consult.

**Pull request merged**
