### PR TITLE
add lgtm integration

### PR DESCRIPTION
**Pull request by wholmgren**
https://lgtm.com/projects/g/SolarArbiter/solarforecastarbiter-core/overview/

also enabled pull request review integration in github organization settings

### CODE REVIEW

**Comment by wholmgren** [comment]
Thanks for checking. Looks like their yaml spec has changed since I first did this in https://github.com/pvlib/pvlib-python/pull/561

**Comment by wholmgren** [comment]
here's their documentation: https://help.semmle.com/lgtm-enterprise/user/help/lgtm.yml-configuration-file.html

**Comment by lboeman** [comment]
> Thanks for checking. Looks like their yaml spec has changed since I first did this in [pvlib/pvlib-python#561](https://github.com/pvlib/pvlib-python/pull/561)

It looks like the _.lgtm.yml_ is written correctly, and the pvlib version isn't suffering from the same issue. The only difference I can see is the lack of newline at the end of the .yml file which perhaps is affecting parsing?

**Comment by wholmgren** [comment]
`generated` is a valid tag: https://help.semmle.com/lgtm-enterprise/user/help/file-classification.html#built-in-tags

I think LGTM config must be in the head master, not the merge candidate. Tony's not here, so let's merge it and find out!

**Pull request merged**
